name: "Coveralls"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coveralls:
    strategy:
      matrix:
        ruby-version:
          - "3.3"
        rails-version:
          - "7.1"
        continue-on-error: [true]
    name: ${{ format('Coverage (Ruby {0}, Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.continue-on-error }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.rails-version }}.gemfile
      RAILS_ENV: test
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Run tests, report coverage
        run: |
          bin/bundle install --retry 3 --quiet
          bin/bundle exec rails db:drop
          bin/bundle exec rails db:create
          bin/bundle exec rails db:migrate
          bin/bundle exec rails test:db
